version: "3"
services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: notesdb
    ports:
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
